### PR TITLE
fix: add verification without redis index

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Conjunction with https://github.com/slsa-framework/slsa-github-generator/pull/330

### CODE REVIEW

**Comment by asraa** [comment]
Verified the v1.1.0 release (after modifying the intoto.jsonl to have the certPEM embedded):
```
$ go run . -artifact-path ~/Downloads/slsa-builder-go-linux-amd64 -provenance ../slsa-github-generator/slsa-builder-go-linux-amd64.intoto.jsonl -source github.com/slsa-framework/slsa-github-generator **-tag v1.1.0**
Signing certificate information:
 {
	"caller": "slsa-framework/slsa-github-generator",
	"commit": "96b2223638c12b5b5f4fc55dd45e6ced5cb830de",
	"job_workflow_ref": "/slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@refs/heads/main",
	"trigger": "push",
	"issuer": "https://token.actions.githubusercontent.com"
}
PASSED: Verified SLSA provenance
```

**Comment by asraa** [comment]
This will require a new cut of the verifier.

**Review by laurentsimon — APPROVED** [review]
I think this changes protects us against artifact hash squatting as well, correct?

**Comment by laurentsimon** [comment]
> This will require a new cut of the verifier.

timely, for the v1.1.0 release.

**Comment by asraa** [comment]
> I think this changes protects us against artifact hash squatting as well, correct?

Yep! It does, all the info is now in the uploaded artifacts

**Comment by laurentsimon** [comment]
The pre-submits are failing because many tests use the old format, and rekor is failing. @asraa how about merging anyway so that we can verify the e2e tests work at HEAD? (and then cut the release)

**Pull request merged**
