### PR TITLE
feat: add ramonpetgrave64 as CODEOWNER

### PR DESCRIPTION
**Pull request by ramonpetgrave64**
adding myself as CODEOWNER

### CODE REVIEW

**Comment by ramonpetgrave64** [comment]
@laurentsimon

**Review by laurentsimon — APPROVED** [review]
Welcome to the team, and great job ramping up!

**Comment by ramonpetgrave64** [comment]
Thanks!

**Review by kpk47 — COMMENTED** [review]
I was a little slow on the draw, but I also approve. Welcome to the team!

**Pull request merged**
