### PR TITLE
fix: remove signing certificate output

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Fixes https://github.com/slsa-framework/slsa-verifier/issues/156

Updates README.md with the new output.

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]

**Comment by laurentsimon** [comment]
lots of really interesting error messages in the log. One I had not seen before: ```Getting rekor entry error error searching rekor entries: [POST /api/v1/log/entries/retrieve][400] searchLogQueryBadRequest  &{Code:400 Message:invalid public key: failure decoding PEM}, trying Redis search index to find entries by subject digest``` ... maybe that's one that'ex expected given the unit tests actually.

May be useful to separate the list of message by a comma.

**Comment by asraa** [comment]
Oh, the error messages were from https://github.com/slsa-framework/slsa-verifier/pull/159, not this PR.

error messages were added with a separated comma: https://github.com/asraa/slsa-verifier/blob/0c6f7c68bde9fd305579e11f86e40a79019e2451/pkg/rekor.go#L394

Maybe a newline? I"ll do that in the follow-up, not this PR

**Comment by asraa** [comment]
> One I had not seen before: Getting rekor entry error error searching rekor entries: [POST /api/v1/log/entries/retrieve][400] searchLogQueryBadRequest &{Code:400 Message:invalid public key: failure decoding PEM}, trying Redis search index to find entries by subject digest ... maybe that's one that'ex expected given the unit tests actually.

I saw this one too, and I realize it's likely because there was no certificate PEM in the intoto envelope for the older builder tests. So rekor fails to decode  the empty string PEM. Just added an error condition to prevent Rekor query if the cert is empty, so that'll be a clearer error message.

**Comment by laurentsimon** [comment]
Ready to merge?

**Comment by asraa** [comment]
Yes!

**Pull request merged**
