### PR TITLE
release: v1.0.1 patch release

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

This sets the expected sha256 of the v1.0.1 slsa-verifier released binary.

How to LGTM this PR (I'll work on a proper doc for this in https://github.com/slsa-framework/slsa-github-generator/issues/112):

1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.0.1
2. Clone the slsa-verifier repo, compile and verify the provenance:
```
$ git clone git@github.com:slsa-framework/slsa-verifier.git
$ cd slsa-verifier
$ (Optional: git checkout tags/v1.0.1)
$ go run . -artifact-path slsa-verifier-linux-amd64 -provenance slsa-verifier-linux-amd64.intoto.jsonl -source github.com/slsa-framework/slsa-verifier -tag v1.0.1 -branch release/v1.0
```
3. Get the hash.
Either:
```
cat slsa-verifier-linux-amd64.intoto.jsonl | jq -r '.payload' | base64 -d | jq -r '.subject[0].digest.sha256'
```
or

```
sha256sum slsa-verifier-linux-amd64
```

The output hash should be the hash I'm updating to in this PR. If they match, LGTM. If they don't, someone tampered with the released binary and don't LGTM

### CODE REVIEW

**Comment by asraa** [comment]
ah oops! the branch is release/v1.0. updating instructions.

**Comment by asraa** [comment]
I think there's one more error of this sharding problem, at least at slsa-verifier head.

**Comment by laurentsimon** [comment]
Worked:
```shell
$ go run . -artifact-path slsa-verifier-linux-amd64 -provenance slsa-verifier-linux-amd64.intoto.jsonl -source github.com/slsa-framework/slsa-verifier -tag v1.0.1 -branch release/v1.0

Signing certificate information:
 {
	"caller": "slsa-framework/slsa-verifier",
	"commit": "eea3a5d3af9370a6a35946fa24e47a426c3f4576",
	"job_workflow_ref": "/slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@refs/tags/v0.0.1",
	"trigger": "push",
	"issuer": "https://token.actions.githubusercontent.com"
}
PASSED: Verified SLSA provenance

```

**Review by laurentsimon — APPROVED** [review]
Verified on my end. Thanks!

**Pull request merged**
