### PR TITLE
test: Add test data for v1.8.0

### PR DESCRIPTION
**Pull request by ianlewis**

### CODE REVIEW

**Comment by ianlewis** [comment]
The container based builder now generates `intoto.build.slsa` files so I'm not sure the tests will still work.

**Comment by laurentsimon** [comment]
> The container based builder now generates `intoto.build.slsa` files so I'm not sure the tests will still work.

is that a breaking change? @asraa ?

**Comment by rbehjati** [comment]
> > The container based builder now generates `intoto.build.slsa` files so I'm not sure the tests will still work.
> 
> is that a breaking change? @asraa ? The only user to date is [Oak](https://github.com/slsa-framework/slsa-github-generator/network/dependents?package_id=UGFja2FnZS0zNzEyNzkyOTU5) , so we should be safe with this change.
> 
> @rbehjati will you be able to handle this name update without breaking?

We are currently using builder_docker-based_slsa3.yml@v1.6.0. We should be able to handle the name change when we update the version to v1.8.0. But also if `intoto.build.slsa` is the provenance name, we pass in a custom name to the workflow via `provenance-name`. So we might not even be affected.

**Review by laurentsimon — COMMENTED** [review]
Shall we add the regression tests for BYOB, Maven and Gradle in this PR?

For BYOB: examples from https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.delegator-generic.workflow_dispatch.main.checkout.slsa3.yml (and maybe https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.delegator-lowperms.workflow_dispatch.main.default.slsa3.yml) can be added to
https://github.com/slsa-framework/example-package/blob/main/.github/workflows/verifier-e2e.all.workflow_dispatch.main.all.slsa3.yml

For Maven / Gradle: Once comments in https://github.com/slsa-framework/slsa-github-generator/pull/2538 are addressed and the PR is merged, we can use code from https://github.com/slsa-framework/example-package/pull/253 to update https://github.com/slsa-framework/example-package/blob/main/.github/workflows/verifier-e2e.all.workflow_dispatch.main.all.slsa3.yml

Wdut?

**Review by laurentsimon — COMMENTED** [review]
we'll add the nodejs tests after it's GA?

**Comment by ianlewis** [comment]
> we'll add the nodejs tests after it's GA?

Yeah, I can maybe take a stab at doing it before GA but on a later PR for sure.

**Comment by ianlewis** [comment]
> Shall we add the regression tests for BYOB, Maven and Gradle in this PR?
> 
> For BYOB: examples from https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.delegator-generic.workflow_dispatch.main.checkout.slsa3.yml (and maybe https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.delegator-lowperms.workflow_dispatch.main.default.slsa3.yml) can be added to https://github.com/slsa-framework/example-package/blob/main/.github/workflows/verifier-e2e.all.workflow_dispatch.main.all.slsa3.yml
> 
> For Maven / Gradle: Once comments in [slsa-framework/slsa-github-generator#2538](https://github.com/slsa-framework/slsa-github-generator/pull/2538) are addressed and the PR is merged, we can use code from [slsa-framework/example-package#253](https://github.com/slsa-framework/example-package/pull/253) to update https://github.com/slsa-framework/example-package/blob/main/.github/workflows/verifier-e2e.all.workflow_dispatch.main.all.slsa3.yml
> 
> Wdut?

Nothing stops us from adding it in a later PR. Esp. if we need to do another release in order to release it to beta.

**Review by laurentsimon — APPROVED** [review]

**Pull request merged**
