### PR TITLE
Request for membership

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- I would like request for membership.

My contributions https://github.com/slsa-framework/slsa-verifier/pulls?q=is%3Apr+author%3Anaveensrinivasan

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@laurentsimon Let me know if you can take a feature similar to this https://github.com/slsa-framework/slsa-github-generator/pull/546

**Comment by naveensrinivasan** [comment]
> @laurentsimon Let me know if you can take a feature similar to this [slsa-framework/slsa-github-generator#546](https://github.com/slsa-framework/slsa-github-generator/pull/546)

I will do something similar to this https://github.com/slsa-framework/slsa-github-generator/pull/651 and also enable a way to publish Test Coverage without using an external service.

**Comment by laurentsimon** [comment]
We don't have a ton of AIs on this repo, but I'll keep you posted if something comes to mind. In the meantime, feel free to browse existing issues.

**Comment by ianlewis** [comment]
I'm going to close this as it's pretty old. Feel free to contribute and resubmit! :)

**Pull request closed without merging**
