### PR TITLE
chore: update docs for release v2.1.0

### PR DESCRIPTION
**Pull request by asraa**
#label:release v2.1.0

### CODE REVIEW

**Comment by asraa** [comment]
You can use this script to verify each of the assets: https://gist.github.com/asraa/e4b034afdfbc8d7b45ffcbbf0ef74f77

**Review by laurentsimon — APPROVED** [review]
I verified all the binaries match the provenance.

**Comment by asraa** [comment]
There's something wrong with the references check, I spent a little time debugging but I'll revisit tomorrow.

**Comment by ianlewis** [comment]
> There's something wrong with the references check, I spent a little time debugging but I'll revisit tomorrow.

I think I found and fixed the issue on #533

**Pull request merged**
